C
C  This file is part of MUMPS 5.2.0, released
C  on Thu Apr 18 09:55:07 UTC 2019
C
C
C  Copyright 1991-2019 CERFACS, CNRS, ENS Lyon, INP Toulouse, Inria,
C  Mumps Technologies, University of Bordeaux.
C
C  This version of MUMPS is provided to you free of charge. It is
C  released under the CeCILL-C license:
C  http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html
C
      SUBROUTINE MUMPS_TPS_M_RETURN()
      RETURN
      END SUBROUTINE MUMPS_TPS_M_RETURN
